# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('data_evento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Desejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lista.Casal')),
            ],
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='desejos',
            name='desejo',
            field=models.ManyToManyField(to='app_lista.Presente'),
        ),
    ]
